# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/advance_mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_advancemode = QtWidgets.QLabel(self.centralwidget)
        self.label_advancemode.setGeometry(QtCore.QRect(0, 0, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_advancemode.setFont(font)
        self.label_advancemode.setObjectName("label_advancemode")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 160, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setObjectName("label")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Apply_advancemode_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Apply_advancemode_btn.setGeometry(QtCore.QRect(460, 480, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Apply_advancemode_btn.setFont(font)
        self.Apply_advancemode_btn.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;   /* Optional background color */\n"
"    border-radius: 20px;          /* Optional: rounded corners */\n"
"\n"
"}rgb(255, 255, 255)")
        self.Apply_advancemode_btn.setObjectName("Apply_advancemode_btn")
        self.OK_advancemode_btn = QtWidgets.QPushButton(self.centralwidget)
        self.OK_advancemode_btn.setGeometry(QtCore.QRect(630, 480, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.OK_advancemode_btn.setFont(font)
        self.OK_advancemode_btn.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;   /* Optional background color */\n"
"    border-radius: 20px;          /* Optional: rounded corners */\n"
"\n"
"}rgb(255, 255, 255)")
        self.OK_advancemode_btn.setObjectName("OK_advancemode_btn")
        self.GeneratorText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.GeneratorText.setGeometry(QtCore.QRect(280, 160, 400, 250))

        # Font monospace chuẩn code
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.GeneratorText.setFont(font)

        # Không tự xuống dòng
        self.GeneratorText.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)

        # Thiết lập tab = 4 spaces chuẩn Python
        metrics = QtGui.QFontMetrics(font)
        self.GeneratorText.setTabStopDistance(4 * metrics.horizontalAdvance(' '))
        self.GeneratorText.setGeometry(QtCore.QRect(280, 160, 400, 250))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.GeneratorText.setFont(font)
        self.GeneratorText.setObjectName("GeneratorText")

        template = (
        "def generator(t):\n"
        "    # User-defined reference signal\n"
        "    # Example:\n"
        "    # output = sin(t)\n"
        "    # End User-defined reference signal\n"
        "    output = 150*np.sin(2*t)\n"
        "    return output\n"
        )
        self.GeneratorText.setPlainText(template)
        self.Status_import_label = QtWidgets.QLabel(self.centralwidget)
        self.Status_import_label.setGeometry(QtCore.QRect(20, 340, 271, 31))
        self.Status_import_label.setText("")
        self.Status_import_label.setObjectName("Status_import_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_advancemode.setText(_translate("MainWindow", "ADVANCE MODE"))
        self.label.setText(_translate("MainWindow", "Please import your code"))
        self.Apply_advancemode_btn.setText(_translate("MainWindow", "Apply"))
        self.OK_advancemode_btn.setText(_translate("MainWindow", "OK"))
