# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/input_ref.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Normal_mode_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Normal_mode_btn.setGeometry(QtCore.QRect(130, 210, 201, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Normal_mode_btn.setFont(font)
        self.Normal_mode_btn.setStyleSheet("QPushButton {\n"
"    background-color: #7FDEFF;   /* blue */\n"
"    border-radius: 20px;         /* rounded corners */\n"
"\n"
"}")
        self.Normal_mode_btn.setObjectName("Normal_mode_btn")
        self.Advance_mode_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Advance_mode_btn.setGeometry(QtCore.QRect(430, 210, 201, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Advance_mode_btn.setFont(font)
        self.Advance_mode_btn.setStyleSheet("QPushButton {\n"
"    background-color: #FAEBA2;   /* yellow */\n"
"    border-radius: 20px;         /* rounded corners */\n"
"}")
        self.Advance_mode_btn.setObjectName("Advance_mode_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Normal_mode_btn.setText(_translate("MainWindow", "NORMAL MODE"))
        self.Advance_mode_btn.setText(_translate("MainWindow", "ADVANCE MODE"))
