# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1276, 708)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_label = QtWidgets.QLabel(self.centralwidget)
        self.main_label.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.main_label.setStyleSheet("QLineEdit {\n"
"    background-color: #E0F7FA;   /* Light cyan */\n"
"    color: #000000;              /* Text color */\n"
"}\n"
"")
        self.main_label.setText("")
        self.main_label.setPixmap(QtGui.QPixmap("ui\\../resources/images/2.jpg"))
        self.main_label.setScaledContents(True)
        self.main_label.setObjectName("main_label")
        self.input_btn = QtWidgets.QPushButton(self.centralwidget)
        self.input_btn.setGeometry(QtCore.QRect(25, 153, 100, 100))
        self.input_btn.setAutoFillBackground(False)
        self.input_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../resources/images/Input.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.input_btn.setIcon(icon)
        self.input_btn.setIconSize(QtCore.QSize(100, 100))
        self.input_btn.setFlat(True)
        self.input_btn.setObjectName("input_btn")
        self.ANN_controller_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ANN_controller_btn.setGeometry(QtCore.QRect(310, 118, 380, 280))
        self.ANN_controller_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\../resources/images/ANN-controller.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ANN_controller_btn.setIcon(icon1)
        self.ANN_controller_btn.setIconSize(QtCore.QSize(375, 280))
        self.ANN_controller_btn.setFlat(True)
        self.ANN_controller_btn.setObjectName("ANN_controller_btn")
        self.DC_motor_btn = QtWidgets.QPushButton(self.centralwidget)
        self.DC_motor_btn.setGeometry(QtCore.QRect(795, 198, 191, 111))
        self.DC_motor_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui\\../resources/images/DC-motor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DC_motor_btn.setIcon(icon2)
        self.DC_motor_btn.setIconSize(QtCore.QSize(180, 100))
        self.DC_motor_btn.setFlat(True)
        self.DC_motor_btn.setObjectName("DC_motor_btn")
        self.Output_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Output_btn.setGeometry(QtCore.QRect(1135, 202, 131, 131))
        self.Output_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui\\../resources/images/Output_Graph-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Output_btn.setIcon(icon3)
        self.Output_btn.setIconSize(QtCore.QSize(145, 140))
        self.Output_btn.setFlat(True)
        self.Output_btn.setObjectName("Output_btn")
        self.User_guide_btn = QtWidgets.QPushButton(self.centralwidget)
        self.User_guide_btn.setGeometry(QtCore.QRect(30, 540, 81, 91))
        self.User_guide_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ui\\../resources/images/user-guide-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.User_guide_btn.setIcon(icon4)
        self.User_guide_btn.setIconSize(QtCore.QSize(81, 91))
        self.User_guide_btn.setFlat(True)
        self.User_guide_btn.setObjectName("User_guide_btn")
        self.sampling_time_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.sampling_time_edit.setGeometry(QtCore.QRect(430, 70, 151, 20))
        self.sampling_time_edit.setStyleSheet("QLineEdit {\n"
"    background-color: #E0F7FA;   /* Light cyan */\n"
"    color: #000000;              /* Text color */\n"
"}")
        self.sampling_time_edit.setObjectName("sampling_time_edit")
        self.Restart_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Restart_btn.setGeometry(QtCore.QRect(1200, 30, 51, 51))
        self.Restart_btn.setStyleSheet("")
        self.Restart_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ui\\../resources/images/restart_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Restart_btn.setIcon(icon5)
        self.Restart_btn.setIconSize(QtCore.QSize(50, 50))
        self.Restart_btn.setObjectName("Restart_btn")
        self.Run_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Run_btn.setGeometry(QtCore.QRect(1120, 30, 51, 51))
        self.Run_btn.setStyleSheet("")
        self.Run_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ui\\../resources/images/start_button.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Run_btn.setIcon(icon6)
        self.Run_btn.setIconSize(QtCore.QSize(50, 50))
        self.Run_btn.setObjectName("Run_btn")
        self.Run_time_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Run_time_input.setGeometry(QtCore.QRect(730, 70, 151, 20))
        self.Run_time_input.setStyleSheet("QLineEdit {\n"
"    background-color: #E0F7FA;   /* Light cyan */\n"
"    color: #000000;              /* Text color */\n"
"}")
        self.Run_time_input.setObjectName("Run_time_input")
        self.Run_time_label = QtWidgets.QLabel(self.centralwidget)
        self.Run_time_label.setGeometry(QtCore.QRect(610, 70, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Run_time_label.setFont(font)
        self.Run_time_label.setObjectName("Run_time_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1276, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Run_time_label.setText(_translate("MainWindow", "RUN TIME (s)"))
