# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Train.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from train_plots import TrainingPlotWindow
import numpy as np

os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
os.environ["QT_ENABLE_HIGHDPI_SCALING"] = "1"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(370, 140, 71, 16))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(360, 580, 91, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 90, 111, 16))
        self.label.setObjectName("label")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(250, 580, 91, 21))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(190, 620, 231, 16))
        self.label_15.setObjectName("label_15")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(130, 580, 91, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(210, 40, 381, 151))
        self.frame.setStyleSheet("QFrame{\n"
"background-color:rgb(166, 166, 166);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(10, 50, 361, 91))
        self.frame_8.setStyleSheet("QFrame{\n"
"background-color: #d9d9d9;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(10, 20, 341, 31))
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_18 = QtWidgets.QLabel(self.frame_9)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 41, 16))
        self.label_18.setObjectName("label_18")
        self.progressBar = QtWidgets.QProgressBar(self.frame_9)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setGeometry(QtCore.QRect(110, 7, 175, 20))
        self.progressBar.setRange(0, 100)
        self.progressBar.setValue(0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setFormat("%v iterations")
        self.progressBar.setStyleSheet("""
QProgressBar {
    background-color: white;
    text-align: center;
}
QProgressBar::chunk {
    background-color: #87CEEB;
    margin: 2px;
}
""")
        self.label_19 = QtWidgets.QLabel(self.frame_9)
        self.label_19.setGeometry(QtCore.QRect(90, 10, 16, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_9)
        self.label_20.setGeometry(QtCore.QRect(300, 10, 21, 16))
        self.label_20.setObjectName("label_20")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setGeometry(QtCore.QRect(160, 0, 41, 20))
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 60, 91, 21))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"background-color: #a6a6a6;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 60, 91, 21))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"background-color: #a6a6a6;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 60, 91, 21))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"background-color: #a6a6a6;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.frame_13 = QtWidgets.QFrame(self.frame)
        self.frame_13.setGeometry(QtCore.QRect(10, 10, 351, 31))
        self.frame_13.setStyleSheet("QFrame {\n"
"background-color: #1800ad;\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_17 = QtWidgets.QLabel(self.frame_13)
        self.label_17.setGeometry(QtCore.QRect(20, 5, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("QLabel{\n"
"color: white;\n"
"}")
        self.label_17.setObjectName("label_17")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(250, 640, 91, 21))
        self.pushButton_8.setObjectName("pushButton_8")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(330, 560, 111, 18))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(160, 560, 111, 18))
        self.checkBox_2.setObjectName("checkBox_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_6.setText(_translate("MainWindow", "10000"))
        self.pushButton_5.setText(_translate("MainWindow", "Cancel"))
        self.label.setText(_translate("MainWindow", "Network Architecture"))
        self.pushButton_7.setText(_translate("MainWindow", "OK"))
        self.label_15.setText(_translate("MainWindow", "Or you can use default parameters by pressing"))
        self.pushButton_6.setText(_translate("MainWindow", "Train Network"))
        self.label_18.setText(_translate("MainWindow", "Epochs"))
        self.label_19.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "100"))
        self.label_4.setText(_translate("MainWindow", "Progress"))
        self.pushButton_2.setText(_translate("MainWindow", "Performance"))
        self.pushButton_4.setText(_translate("MainWindow", "Cancel"))
        self.pushButton_3.setText(_translate("MainWindow", "Stop Training"))
        self.label_17.setText(_translate("MainWindow", "Neural Network Training"))
        self.pushButton_8.setText(_translate("MainWindow", "Default"))
        self.checkBox_3.setText(_translate("MainWindow", "Use Test Data"))
        self.checkBox_2.setText(_translate("MainWindow", "Use Validation Data"))


if __name__ == "__main__":
    QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
    QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle("Fusion")

    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    plot_win = TrainingPlotWindow(MainWindow)

    epoch_total = 100
    epoch_count = 0
    def set_epoch_count(current: int, total: int = None):
        """Update the progress bar from your training loop."""
        if total is not None:
            ui.progressBar.setRange(0, int(total))
        ui.progressBar.setValue(int(current))
    demo_timer = QtCore.QTimer()
    demo_timer.setInterval(80)
    def _tick():
        global epoch_count, epoch_total
        if epoch_count < epoch_total:
            epoch_count += 1
            set_epoch_count(epoch_count, epoch_total)
        else:
            demo_timer.stop()
    demo_timer.timeout.connect(_tick)

    def _demo_update():
        # Simulated data
        t = np.linspace(0, 50, 500)
        inp   = np.sin(0.4*t) + 0.2*np.random.randn(len(t))
        plant = np.sin(0.4*t + 0.6) + 0.3*np.random.randn(len(t))
        err   = (plant - inp) * 0.01
        nn    = inp + 0.1*np.random.randn(len(t))
        plot_win.update_plots(t, inp, plant, err, nn)

    ui.pushButton_2.clicked.connect(_demo_update)
    ui.pushButton_2.clicked.connect(plot_win.show)
    ui.pushButton_3.clicked.connect(demo_timer.stop)
    ui.pushButton_4.clicked.connect(MainWindow.close)

    MainWindow.show()
    QtCore.QTimer.singleShot(0, lambda: (set_epoch_count(0, epoch_total), demo_timer.start()))
    sys.exit(app.exec_())
