# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Model.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import sys
import subprocess, json
from PyQt5 import QtCore, QtGui, QtWidgets

os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
os.environ["QT_ENABLE_HIGHDPI_SCALING"] = "1"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 50, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 120, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(430, 120, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(360, 80, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(380, 160, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(250, 190, 91, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(250, 220, 91, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(250, 240, 91, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(250, 260, 91, 16))
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 190, 121, 21))
        self.pushButton.setStyleSheet("QPushButton {\n"
"background-color: gray;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(430, 240, 91, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(430, 220, 91, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(430, 260, 91, 16))
        self.label_12.setObjectName("label_12")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(350, 190, 41, 16))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(350, 220, 41, 16))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(350, 240, 41, 16))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(350, 260, 41, 16))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(530, 220, 41, 16))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(380, 100, 71, 16))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(280, 140, 71, 16))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(470, 140, 71, 16))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(530, 240, 41, 16))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(530, 260, 41, 16))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 280, 91, 21))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"background-color: gray;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(370, 280, 91, 21))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"background-color: gray;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(480, 280, 91, 21))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"background-color: gray;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(370, 310, 101, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(380, 330, 81, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(390, 350, 61, 16))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(280, 370, 111, 18))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(450, 370, 111, 18))
        self.checkBox_3.setObjectName("checkBox_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(480, 390, 91, 21))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"background-color: gray;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(250, 390, 91, 21))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"background-color: gray;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(370, 390, 91, 21))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"background-color: gray;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(310, 430, 231, 16))
        self.label_15.setObjectName("label_15")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(370, 450, 91, 21))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"background-color: gray;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(220, 0, 381, 501))
        self.frame.setStyleSheet("QFrame{\n"
"background-color:rgb(166, 166, 166);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 50, 361, 441))
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color: #d9d9d9;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 20, 341, 91))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(10, 130, 341, 131))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(10, 280, 341, 91))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(10, 380, 341, 51))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(10, 10, 351, 31))
        self.frame_7.setStyleSheet("QFrame {\n"
"background-color: #1800ad;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_16 = QtWidgets.QLabel(self.frame_7)
        self.label_16.setGeometry(QtCore.QRect(20, 5, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel{\n"
"color: white;\n"
"}")
        self.label_16.setObjectName("label_16")
        self.frame.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.pushButton.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_6.raise_()
        self.lineEdit_7.raise_()
        self.lineEdit_8.raise_()
        self.lineEdit_9.raise_()
        self.lineEdit_10.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.lineEdit_11.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.label_15.raise_()
        self.pushButton_8.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Network Architecture"))
        self.label_2.setText(_translate("MainWindow", "No. of Delayed Plant Inputs"))
        self.label_3.setText(_translate("MainWindow", "No. of Delayed Plant Outputs"))
        self.label_4.setText(_translate("MainWindow", "Size of Hidden Layers"))
        self.label_5.setText(_translate("MainWindow", "Training Data"))
        self.label_6.setText(_translate("MainWindow", "Training Samples"))
        self.label_7.setText(_translate("MainWindow", "Max Plant Input"))
        self.label_8.setText(_translate("MainWindow", "Min Plant Input"))
        self.label_9.setText(_translate("MainWindow", "Max Interval (sec)"))
        self.pushButton.setText(_translate("MainWindow", "Import Network Weight"))
        self.label_10.setText(_translate("MainWindow", "Min Plant Output"))
        self.label_11.setText(_translate("MainWindow", "Max Plant Output"))
        self.label_12.setText(_translate("MainWindow", "Max Interval (sec)"))
        self.lineEdit.setText(_translate("MainWindow", ""))
        self.lineEdit_2.setText(_translate("MainWindow", ""))
        self.lineEdit_3.setText(_translate("MainWindow", ""))
        self.lineEdit_4.setText(_translate("MainWindow", ""))
        self.lineEdit_5.setText(_translate("MainWindow", ""))
        self.lineEdit_6.setText(_translate("MainWindow", ""))
        self.lineEdit_7.setText(_translate("MainWindow", ""))
        self.lineEdit_8.setText(_translate("MainWindow", ""))
        self.lineEdit_9.setText(_translate("MainWindow", ""))
        self.lineEdit_10.setText(_translate("MainWindow", ""))
        self.pushButton_2.setText(_translate("MainWindow", "Generate Data"))
        self.pushButton_3.setText(_translate("MainWindow", "Export Data"))
        self.pushButton_4.setText(_translate("MainWindow", "Import Data"))
        self.label_13.setText(_translate("MainWindow", "Training Parameters"))
        self.label_14.setText(_translate("MainWindow", "Training Epochs"))
        self.lineEdit_11.setText(_translate("MainWindow", ""))
        self.checkBox_2.setText(_translate("MainWindow", "Use Validation Data"))
        self.checkBox_3.setText(_translate("MainWindow", "Use Test Data"))
        self.pushButton_5.setText(_translate("MainWindow", "Cancel"))
        self.pushButton_6.setText(_translate("MainWindow", "Train Network"))
        self.pushButton_7.setText(_translate("MainWindow", "OK"))
        self.label_15.setText(_translate("MainWindow", "Or you can use default parameters by pressing"))
        self.pushButton_8.setText(_translate("MainWindow", "Default"))
        self.label_16.setText(_translate("MainWindow", "Model Configurations"))

class Utils:
    """Utility class for validating inputs and launching actions."""
    def __init__(self, ui, window):
        self.ui = ui
        self.window = window

        # Required fields
        self.required_edits_all = [
            ui.lineEdit_6,   # Size of hidden layers (int)
            ui.lineEdit_7,   # No. delayed plant inputs (int)
            ui.lineEdit_8,   # No. delayed plant outputs (int)
            ui.lineEdit,     # Training samples (int)
            ui.lineEdit_2,   # Max plant input (L) (float)
            ui.lineEdit_3,   # Min plant input (L) (float)
            ui.lineEdit_4,   # Max interval (L) (float)
            ui.lineEdit_5,   # Min plant output (R) (float)
            ui.lineEdit_9,   # Max plant output (R) (float)
            ui.lineEdit_10,  # Min interval (R) (float)
            ui.lineEdit_11,  # Training epochs (int)
        ]
        # Same list without epochs for Generate Data
        self.required_edits_no_epoch = [w for w in self.required_edits_all if w is not ui.lineEdit_11]

        self._setup_validators()
        self._connect_signals()
        self.update_buttons_state()

    # -------------------- setup --------------------
    def _setup_validators(self):
        int_validator    = QtGui.QIntValidator(-1_000_000, 1_000_000, self.window)
        double_validator = QtGui.QDoubleValidator(-1e9, 1e9, 6, self.window)
        double_validator.setNotation(QtGui.QDoubleValidator.StandardNotation)

        # integer fields
        for w in [self.ui.lineEdit_6, self.ui.lineEdit_7, self.ui.lineEdit_8, self.ui.lineEdit, self.ui.lineEdit_11]:
            w.setValidator(int_validator)
        # float fields
        for w in [self.ui.lineEdit_2, self.ui.lineEdit_3, self.ui.lineEdit_4, self.ui.lineEdit_5, self.ui.lineEdit_9, self.ui.lineEdit_10]:
            w.setValidator(double_validator)

        # optional placeholders
        self.ui.lineEdit_6.setPlaceholderText("e.g. 9")
        self.ui.lineEdit_7.setPlaceholderText("e.g. 3")
        self.ui.lineEdit_8.setPlaceholderText("e.g. 2")
        self.ui.lineEdit.setPlaceholderText("e.g. 100000")
        self.ui.lineEdit_11.setPlaceholderText("e.g. 100")

    def _connect_signals(self):
        for w in self.required_edits_all:
            w.textChanged.connect(self.update_buttons_state)

    # -------------------- validation --------------------
    @staticmethod
    def _is_acceptably_filled(widget):
        text = widget.text().strip()
        if not text:
            return False
        v = widget.validator()
        if v is None:
            return True
        state, _, _ = v.validate(text, 0)
        return state == QtGui.QValidator.Acceptable

    def all_filled_and_valid(self):
        # For Train: all fields incl. epochs
        return all(self._is_acceptably_filled(w) for w in self.required_edits_all)

    def all_filled_and_valid_no_epoch(self):
        # For Generate Data: all except epochs
        return all(self._is_acceptably_filled(w) for w in self.required_edits_no_epoch)

    def update_buttons_state(self):
        self.ui.pushButton_6.setEnabled(self.all_filled_and_valid())            # Train
        self.ui.pushButton_2.setEnabled(self.all_filled_and_valid_no_epoch())   # Generate Data

    # -------------------- collectors --------------------
    def collect_common_parameters(self):
        ui = self.ui
        return {
            "hidden":        int(ui.lineEdit_6.text()),
            "delay_in":      int(ui.lineEdit_7.text()),
            "delay_out":     int(ui.lineEdit_8.text()),
            "train_samples": int(ui.lineEdit.text()),
            "max_in_l":      float(ui.lineEdit_2.text()),
            "min_in_l":      float(ui.lineEdit_3.text()),
            "max_int_l":     float(ui.lineEdit_4.text()),
            "min_in_r":      float(ui.lineEdit_5.text()),
            "max_in_r":      float(ui.lineEdit_9.text()),
            "max_int_r":     float(ui.lineEdit_10.text()),
            "use_val":       bool(ui.checkBox_2.isChecked()),
            "use_test":      bool(ui.checkBox_3.isChecked()),
        }

    def collect_train_parameters(self):
        params = self.collect_common_parameters()
        params["epochs"] = int(self.ui.lineEdit_11.text())
        return params

    # -------------------- actions --------------------
    def run_model_train(self):
        if not self.all_filled_and_valid():
            QtWidgets.QMessageBox.warning(self.window, "Invalid input", "Please fill all fields with valid numbers.")
            return
        params = self.collect_train_parameters()
        try:
            subprocess.Popen(
                [sys.executable, "model_train.py", json.dumps(params)],
                creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0)
            )
        except Exception as e:
            QtWidgets.QMessageBox.critical(self.window, "Launch error", str(e))

    def run_generate_data(self):
        if not self.all_filled_and_valid_no_epoch():
            QtWidgets.QMessageBox.warning(self.window, "Invalid input", "Please fill all required fields (epochs not required).")
            return
        params = self.collect_common_parameters()
        try:
            # Adjust script name if yours differs
            subprocess.Popen(
                [sys.executable, "generate_data.py", json.dumps(params)],
                creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0)
            )
        except Exception as e:
            QtWidgets.QMessageBox.critical(self.window, "Launch error", str(e))

    def open_network_weight(self):
        """Open file dialog to select a network weight file (starts in current folder)."""
        options = QtWidgets.QFileDialog.Options()
        options |= QtWidgets.QFileDialog.ReadOnly
        start_dir = os.getcwd()  # current working directory

        file_path, _ = QtWidgets.QFileDialog.getOpenFileName(
            self.window,
            "Select Network Weight File",
            start_dir,
            "All Files (*);;HDF5 Files (*.h5);;Model Files (*.model);;Text Files (*.txt)",
            options=options
        )
        if file_path:
            print(f"Selected weight file: {file_path}")

    def set_default_parameters(self):
        """Fill all fields with default parameter values."""
        ui = self.ui

        # --- Network Architecture ---
        ui.lineEdit_6.setText("9")   
        ui.lineEdit_7.setText("3")   
        ui.lineEdit_8.setText("2")   

        # --- Training Data ---
        ui.lineEdit.setText("100000")
        ui.lineEdit_2.setText("4")   
        ui.lineEdit_3.setText("-1")  
        ui.lineEdit_4.setText("60")  
        ui.lineEdit_5.setText("100000")   
        ui.lineEdit_9.setText("0") 
        ui.lineEdit_10.setText("0")

        # --- Training Parameters ---
        ui.lineEdit_11.setText("100")

        ui.checkBox_2.setChecked(True)
        ui.checkBox_3.setChecked(True)

        self.update_buttons_state()

if __name__ == "__main__":
    QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
    QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle("Fusion")

    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    
    utils = Utils(ui, MainWindow)

    ui.pushButton.clicked.connect(utils.open_network_weight)
    ui.pushButton_2.clicked.connect(utils.run_generate_data)
    ui.pushButton_4.clicked.connect(utils.open_network_weight)
    ui.pushButton_5.clicked.connect(MainWindow.close)
    ui.pushButton_6.clicked.connect(utils.run_model_train)
    ui.pushButton_8.clicked.connect(utils.set_default_parameters)


    MainWindow.show()
    sys.exit(app.exec_())
