# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/model_train.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(386, 199)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.epochs_input = QtWidgets.QLineEdit(self.centralwidget)
        self.epochs_input.setGeometry(QtCore.QRect(160, 100, 71, 16))
        self.epochs_input.setObjectName("epochs_input")
        self.arch_label = QtWidgets.QLabel(self.centralwidget)
        self.arch_label.setGeometry(QtCore.QRect(140, 50, 111, 16))
        self.arch_label.setObjectName("arch_label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 381, 151))
        self.frame.setStyleSheet("QFrame{\n"
"background-color:rgb(166, 166, 166);\n"
"}")
        self.frame.setObjectName("frame")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(10, 50, 361, 91))
        self.frame_8.setStyleSheet("QFrame{\n"
"background-color: #d9d9d9;\n"
"}")
        self.frame_8.setObjectName("frame_8")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(10, 20, 341, 31))
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setObjectName("frame_9")
        self.epochs_label = QtWidgets.QLabel(self.frame_9)
        self.epochs_label.setGeometry(QtCore.QRect(10, 10, 41, 16))
        self.epochs_label.setObjectName("epochs_label")
        self.progress_bar = QtWidgets.QProgressBar(self.frame_9)
        self.progress_bar.setGeometry(QtCore.QRect(110, 7, 175, 20))
        self.progress_bar.setStyleSheet("\n"
"QProgressBar {\n"
"    background-color: white;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #87CEEB;\n"
"    margin: 2px;\n"
"}\n"
"")
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setTextVisible(True)
        self.progress_bar.setObjectName("progress_bar")
        self.progress_min_label = QtWidgets.QLabel(self.frame_9)
        self.progress_min_label.setGeometry(QtCore.QRect(90, 10, 16, 16))
        self.progress_min_label.setObjectName("progress_min_label")
        self.progress_max_label = QtWidgets.QLabel(self.frame_9)
        self.progress_max_label.setGeometry(QtCore.QRect(300, 10, 21, 16))
        self.progress_max_label.setObjectName("progress_max_label")
        self.progress_label = QtWidgets.QLabel(self.frame_8)
        self.progress_label.setGeometry(QtCore.QRect(160, 0, 41, 20))
        self.progress_label.setObjectName("progress_label")
        self.performance_btn = QtWidgets.QPushButton(self.frame_8)
        self.performance_btn.setGeometry(QtCore.QRect(20, 60, 91, 21))
        self.performance_btn.setStyleSheet("QPushButton { background-color: #a6a6a6; }")
        self.performance_btn.setObjectName("performance_btn")
        self.stop_btn = QtWidgets.QPushButton(self.frame_8)
        self.stop_btn.setGeometry(QtCore.QRect(140, 60, 91, 21))
        self.stop_btn.setStyleSheet("QPushButton { background-color: #a6a6a6; }")
        self.stop_btn.setObjectName("stop_btn")
        self.cancel_btn = QtWidgets.QPushButton(self.frame_8)
        self.cancel_btn.setGeometry(QtCore.QRect(250, 60, 91, 21))
        self.cancel_btn.setStyleSheet("QPushButton { background-color: #a6a6a6; }")
        self.cancel_btn.setObjectName("cancel_btn")
        self.frame_13 = QtWidgets.QFrame(self.frame)
        self.frame_13.setGeometry(QtCore.QRect(10, 10, 351, 31))
        self.frame_13.setStyleSheet("QFrame { background-color: #1800ad; }")
        self.frame_13.setObjectName("frame_13")
        self.title_label = QtWidgets.QLabel(self.frame_13)
        self.title_label.setGeometry(QtCore.QRect(20, 5, 161, 21))
        self.title_label.setStyleSheet("QLabel { color: white; }")
        self.title_label.setObjectName("title_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 386, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.epochs_input.setText(_translate("MainWindow", "10000"))
        self.arch_label.setText(_translate("MainWindow", "Network Architecture"))
        self.epochs_label.setText(_translate("MainWindow", "Epochs"))
        self.progress_bar.setFormat(_translate("MainWindow", "%v iterations"))
        self.progress_min_label.setText(_translate("MainWindow", "0"))
        self.progress_max_label.setText(_translate("MainWindow", "100"))
        self.progress_label.setText(_translate("MainWindow", "Progress"))
        self.performance_btn.setText(_translate("MainWindow", "Performance"))
        self.stop_btn.setText(_translate("MainWindow", "Stop Training"))
        self.cancel_btn.setText(_translate("MainWindow", "Cancel"))
        self.title_label.setText(_translate("MainWindow", "Neural Network Training"))
