# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/model_train.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(386, 199)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(160, 100, 71, 16))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 50, 111, 16))
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 381, 151))
        self.frame.setStyleSheet("QFrame{\n"
"background-color:rgb(166, 166, 166);\n"
"}")
        self.frame.setObjectName("frame")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(10, 50, 361, 91))
        self.frame_8.setStyleSheet("QFrame{\n"
"background-color: #d9d9d9;\n"
"}")
        self.frame_8.setObjectName("frame_8")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(10, 20, 341, 31))
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setObjectName("frame_9")
        self.label_18 = QtWidgets.QLabel(self.frame_9)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 41, 16))
        self.label_18.setObjectName("label_18")
        self.progressBar = QtWidgets.QProgressBar(self.frame_9)
        self.progressBar.setGeometry(QtCore.QRect(110, 7, 175, 20))
        self.progressBar.setStyleSheet("\n"
"QProgressBar {\n"
"    background-color: white;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #87CEEB;\n"
"    margin: 2px;\n"
"}\n"
"")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.label_19 = QtWidgets.QLabel(self.frame_9)
        self.label_19.setGeometry(QtCore.QRect(90, 10, 16, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_9)
        self.label_20.setGeometry(QtCore.QRect(300, 10, 21, 16))
        self.label_20.setObjectName("label_20")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setGeometry(QtCore.QRect(160, 0, 41, 20))
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 60, 91, 21))
        self.pushButton_2.setStyleSheet("QPushButton { background-color: #a6a6a6; }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 60, 91, 21))
        self.pushButton_3.setStyleSheet("QPushButton { background-color: #a6a6a6; }")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 60, 91, 21))
        self.pushButton_4.setStyleSheet("QPushButton { background-color: #a6a6a6; }")
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_13 = QtWidgets.QFrame(self.frame)
        self.frame_13.setGeometry(QtCore.QRect(10, 10, 351, 31))
        self.frame_13.setStyleSheet("QFrame { background-color: #1800ad; }")
        self.frame_13.setObjectName("frame_13")
        self.label_17 = QtWidgets.QLabel(self.frame_13)
        self.label_17.setGeometry(QtCore.QRect(20, 5, 161, 21))
        self.label_17.setStyleSheet("QLabel { color: white; }")
        self.label_17.setObjectName("label_17")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 386, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_6.setText(_translate("MainWindow", "10000"))
        self.label.setText(_translate("MainWindow", "Network Architecture"))
        self.label_18.setText(_translate("MainWindow", "Epochs"))
        self.progressBar.setFormat(_translate("MainWindow", "%v iterations"))
        self.label_19.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "100"))
        self.label_4.setText(_translate("MainWindow", "Progress"))
        self.pushButton_2.setText(_translate("MainWindow", "Performance"))
        self.pushButton_3.setText(_translate("MainWindow", "Stop Training"))
        self.pushButton_4.setText(_translate("MainWindow", "Cancel"))
        self.label_17.setText(_translate("MainWindow", "Neural Network Training"))
