# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/normal_mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_normalmode = QtWidgets.QLabel(self.centralwidget)
        self.label_normalmode.setGeometry(QtCore.QRect(0, 0, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_normalmode.setFont(font)
        self.label_normalmode.setObjectName("label_normalmode")
        self.Random_gen_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Random_gen_btn.setGeometry(QtCore.QRect(160, 110, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.Random_gen_btn.setFont(font)
        self.Random_gen_btn.setStyleSheet("QPushButton {\n"
"    background-color: #ffc234;   /* Optional background color */\n"
"    border-radius: 20px;          /* Optional: rounded corners */\n"
"\n"
"}")
        self.Random_gen_btn.setObjectName("Random_gen_btn")
        self.Manual_gen_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Manual_gen_btn.setGeometry(QtCore.QRect(160, 270, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.Manual_gen_btn.setFont(font)
        self.Manual_gen_btn.setStyleSheet("QPushButton {\n"
"    background-color: #7FDEFF;   /* Optional background color */\n"
"    border-radius: 20px;          /* Optional: rounded corners */\n"
"}")
        self.Manual_gen_btn.setObjectName("Manual_gen_btn")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 60, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 110, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(380, 145, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.RD_max_vel_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.RD_max_vel_line_edit.setGeometry(QtCore.QRect(440, 115, 113, 20))
        self.RD_max_vel_line_edit.setObjectName("RD_max_vel_line_edit")
        self.RD_min_vel_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.RD_min_vel_line_edit.setGeometry(QtCore.QRect(440, 155, 113, 20))
        self.RD_min_vel_line_edit.setObjectName("RD_min_vel_line_edit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(330, 270, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(330, 300, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.man_Stime_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.man_Stime_lineedit.setGeometry(QtCore.QRect(440, 275, 113, 20))
        self.man_Stime_lineedit.setObjectName("man_Stime_lineedit")
        self.man_Veloval_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.man_Veloval_lineedit.setGeometry(QtCore.QRect(440, 312, 113, 20))
        self.man_Veloval_lineedit.setObjectName("man_Veloval_lineedit")
        self.Reset_all_val_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Reset_all_val_btn.setGeometry(QtCore.QRect(20, 490, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Reset_all_val_btn.setFont(font)
        self.Reset_all_val_btn.setStyleSheet("QPushButton {\n"
"    background-color: #0fac04;   /* Optional background color */\n"
"    border-radius: 20px;          /* Optional: rounded corners */\n"
"\n"
"}")
        self.Reset_all_val_btn.setObjectName("Reset_all_val_btn")
        self.Apply_normalmode_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Apply_normalmode_btn.setGeometry(QtCore.QRect(430, 500, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Apply_normalmode_btn.setFont(font)
        self.Apply_normalmode_btn.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;   /* Optional background color */\n"
"    border-radius: 20px;          /* Optional: rounded corners */\n"
"\n"
"}rgb(255, 255, 255)")
        self.Apply_normalmode_btn.setObjectName("Apply_normalmode_btn")
        self.OK_normalmode_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.OK_normalmode_btn_2.setGeometry(QtCore.QRect(600, 500, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.OK_normalmode_btn_2.setFont(font)
        self.OK_normalmode_btn_2.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;   /* Optional background color */\n"
"    border-radius: 20px;          /* Optional: rounded corners */\n"
"\n"
"}rgb(255, 255, 255)")
        self.OK_normalmode_btn_2.setObjectName("OK_normalmode_btn_2")
        self.Status_nor_label = QtWidgets.QLabel(self.centralwidget)
        self.Status_nor_label.setGeometry(QtCore.QRect(20, 380, 351, 21))
        self.Status_nor_label.setText("")
        self.Status_nor_label.setObjectName("Status_nor_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_normalmode.setText(_translate("MainWindow", "NORMAL MODE"))
        self.Random_gen_btn.setText(_translate("MainWindow", "RANDOM GENERATOR"))
        self.Manual_gen_btn.setText(_translate("MainWindow", "MANUAL GENERATOR"))
        self.label_2.setText(_translate("MainWindow", "Velocity Value"))
        self.label_3.setText(_translate("MainWindow", "Max"))
        self.label_4.setText(_translate("MainWindow", "Min"))
        self.label_5.setText(_translate("MainWindow", "Start time (s)"))
        self.label_6.setText(_translate("MainWindow", "Velocity Value"))
        self.Reset_all_val_btn.setText(_translate("MainWindow", "Reset all value"))
        self.Apply_normalmode_btn.setText(_translate("MainWindow", "Apply"))
        self.OK_normalmode_btn_2.setText(_translate("MainWindow", "OK"))
